/*
 * test_template.c — chat templates and stop markers (#2).
 *
 * 1. Goldens: the bytes geist-serve renders today (ported from its
 *    tests/test_template.c), through a single send.
 * 2. Incremental = whole: for every family, sending a conversation turn by
 *    turn (answer + close in between) gives exactly the bytes of rendering
 *    it at once, with and without an end marker generated by the model.
 * 3. Family detection and stop token ids.
 */
#include "template.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int failures;

static void eq(const char *name, const char *want, const char *got) {
    if (want && got && !strcmp(want, got))
        return;
    fprintf(stderr, "FAIL %s\n  want: %s\n  got:  %s\n", name, want ? want : "(null)", got ? got : "(null)");
    failures++;
}

static void check(bool ok, const char *name) {
    if (!ok) {
        fprintf(stderr, "FAIL %s\n", name);
        failures++;
    }
}

/* Render a whole conversation in one send, as geist-serve does. */
static char *whole(enum tpl_family f, size_t n, const geistr_message msgs[]) {
    struct tpl_state st;
    tpl_init(&st, f);
    char *p = tpl_render_send(&st, n, msgs);
    tpl_free(&st);
    return p;
}

static void append(char **acc, const char *s) {
    size_t a = *acc ? strlen(*acc) : 0, b = strlen(s);
    char  *p = realloc(*acc, a + b + 1);
    if (!p)
        abort();
    memcpy(p + a, s, b + 1);
    *acc = p;
}

static const char *marker(enum tpl_family f) {
    switch (f) {
    case TPL_GEMMA3:
        return "<end_of_turn>";
    case TPL_GEMMA4:
        return "<turn|>";
    case TPL_CHATML:
        return "<|im_end|>";
    default:
        return "<|eot_id|>";
    }
}

/* Send turn by turn: every assistant message plays the generated answer. */
static char *incremental(enum tpl_family f, size_t n, const geistr_message msgs[], bool model_marker) {
    struct tpl_state st;
    tpl_init(&st, f);
    char  *acc   = nullptr;
    size_t first = 0;
    for (size_t i = 0; i <= n; i++) {
        if (i < n && strcmp(msgs[i].role, "assistant"))
            continue;
        char *sent = tpl_render_send(&st, i - first, msgs + first);
        append(&acc, sent);
        free(sent);
        if (i == n)
            break;
        append(&acc, msgs[i].content);
        if (model_marker)
            append(&acc, marker(f));
        append(&acc, tpl_answer_close(f, model_marker ? marker(f) : nullptr));
        first = i + 1;
    }
    tpl_free(&st);
    return acc;
}

static const geistr_message CONV[] = {
        {"system", "Be brief."},
        {"user", "Hi"},
        {"assistant", "Hello!"},
        {"user", "Capital of France?"},
};
#define N (sizeof CONV / sizeof CONV[0])

static void goldens(void) {
    char *p = whole(TPL_CHATML, N, CONV);
    eq("chatml",
       "<|im_start|>system\nBe brief.<|im_end|>\n"
       "<|im_start|>user\nHi<|im_end|>\n"
       "<|im_start|>assistant\nHello!<|im_end|>\n"
       "<|im_start|>user\nCapital of France?<|im_end|>\n"
       "<|im_start|>assistant\n",
       p);
    free(p);
    p = whole(TPL_GEMMA4, N, CONV);
    eq("gemma4",
       "<|turn>system\nBe brief.<turn|>\n"
       "<|turn>user\nHi<turn|>\n"
       "<|turn>model\nHello!<turn|>\n"
       "<|turn>user\nCapital of France?<turn|>\n"
       "<|turn>model\n",
       p);
    free(p);
    p = whole(TPL_GEMMA3, N, CONV);
    eq("gemma3 folds system into first user turn",
       "<start_of_turn>user\nBe brief.\n\nHi<end_of_turn>\n"
       "<start_of_turn>model\nHello!<end_of_turn>\n"
       "<start_of_turn>user\nCapital of France?<end_of_turn>\n"
       "<start_of_turn>model\n",
       p);
    free(p);
    p = whole(TPL_LLAMA3, N, CONV);
    eq("llama3",
       "<|start_header_id|>system<|end_header_id|>\n\nBe brief.<|eot_id|>"
       "<|start_header_id|>user<|end_header_id|>\n\nHi<|eot_id|>"
       "<|start_header_id|>assistant<|end_header_id|>\n\nHello!<|eot_id|>"
       "<|start_header_id|>user<|end_header_id|>\n\nCapital of France?<|eot_id|>"
       "<|start_header_id|>assistant<|end_header_id|>\n\n",
       p);
    free(p);
    p = whole(TPL_BITNET, N, CONV);
    eq("bitnet: model card turns, every turn closed by <|eot_id|>",
       "System: Be brief.<|eot_id|>"
       "User: Hi<|eot_id|>"
       "Assistant: Hello!<|eot_id|>"
       "User: Capital of France?<|eot_id|>"
       "Assistant: ",
       p);
    free(p);
    p = whole(TPL_CHATML, 1, (geistr_message[]) {{"user", "Hi"}});
    eq("no system message", "<|im_start|>user\nHi<|im_end|>\n<|im_start|>assistant\n", p);
    free(p);
    p = whole(TPL_CHATML, 2, (geistr_message[]) {{"user", "a"}, {"tool", "x"}});
    eq("unknown role renders as user",
       "<|im_start|>user\na<|im_end|>\n<|im_start|>user\nx<|im_end|>\n<|im_start|>assistant\n", p);
    free(p);
    p = whole(TPL_UNKNOWN, N, CONV);
    check(p == nullptr, "unknown family renders nothing");
    p = whole(TPL_CHATML, 0, (geistr_message[]) {{"user", ""}});
    eq("zero messages = generation prompt only", "<|im_start|>assistant\n", p);
    free(p);
}

static void incremental_equals_whole(void) {
    static const geistr_message long_conv[] = {
            {"system", "Antworte kurz."}, {"user", "Grüße 🌍"}, {"assistant", "Hallo!"},
            {"user", "Und?"},             {"assistant", ""},    {"user", "Noch einmal."},
    };
    static const geistr_message system_first[] = {{"system", "Be brief."}, {"assistant", "Ready."}, {"user", "Go"}};
    static const geistr_message two_systems[]  = {
            {"system", "A"}, {"user", "b"}, {"assistant", "c"}, {"system", "D"}, {"user", "e"}};
    struct {
        const char           *name;
        size_t                n;
        const geistr_message *msgs;
    } convs[] = {
            {"basic", N, CONV},
            {"three rounds, unicode, empty answer", 6, long_conv},
            {"system-only first send (Gemma 3 keeps the fold pending)", 3, system_first},
            {"a later system message", 5, two_systems},
    };
    for (enum tpl_family f = TPL_GEMMA3; f <= TPL_BITNET; f++)
        for (size_t c = 0; c < sizeof convs / sizeof convs[0]; c++)
            for (int m = 0; m < 2; m++) {
                char *a = whole(f, convs[c].n, convs[c].msgs);
                char *b = incremental(f, convs[c].n, convs[c].msgs, m);
                char  name[160];
                snprintf(name, sizeof name, "%s: %s, %s", tpl_family_name(f), convs[c].name,
                         m ? "model ends with its marker" : "answer closed by the runtime");
                eq(name, a, b);
                free(a);
                free(b);
            }
}

static void generation_prompts(void) {
    for (enum tpl_family f = TPL_GEMMA3; f <= TPL_BITNET; f++) {
        char        *p = whole(f, N, CONV);
        const char  *g = tpl_generation_prompt(f);
        const size_t n = strlen(p), k = strlen(g);
        check(p && k > 0 && n >= k && !strcmp(p + n - k, g), "every render ends with the generation prompt");
        free(p);
    }
    check(!strcmp(tpl_generation_prompt(TPL_UNKNOWN), ""), "unknown family: no prompt");
}

static void close_texts(void) {
    eq("chatml close", "<|im_end|>\n", tpl_answer_close(TPL_CHATML, nullptr));
    eq("chatml close after marker", "\n", tpl_answer_close(TPL_CHATML, "<|im_end|>"));
    eq("llama3 close after marker", "", tpl_answer_close(TPL_LLAMA3, "<|eot_id|>"));
    eq("an unrelated end token closes fully", "<|im_end|>\n", tpl_answer_close(TPL_CHATML, "<|end_of_text|>"));
    eq("unknown family", "", tpl_answer_close(TPL_UNKNOWN, nullptr));
}

static void detection(void) {
    check(tpl_family_from_template("{{ '<|turn>system\\n' }}") == TPL_GEMMA4, "fp gemma4");
    check(tpl_family_from_template("<start_of_turn>user") == TPL_GEMMA3, "fp gemma3");
    check(tpl_family_from_template("{{'<|im_start|>' + role}}") == TPL_CHATML, "fp chatml");
    check(tpl_family_from_template("<|start_header_id|>") == TPL_LLAMA3, "fp llama3");
    check(tpl_family_from_template("'\\n\\nBITNETAssistant: '") == TPL_BITNET, "fp bitnet");
    check(tpl_family_from_template("{% for m in messages %}") == TPL_UNKNOWN, "fp unknown");
    check(tpl_family_from_template(nullptr) == TPL_UNKNOWN, "fp null");
    check(tpl_family_from_arch("gemma4") == TPL_GEMMA4 && tpl_family_from_arch("gemma3") == TPL_GEMMA3, "arch gemma");
    check(tpl_family_from_arch("qwen35") == TPL_CHATML, "arch qwen35");
    check(tpl_family_from_arch("bitnet-b1.58") == TPL_BITNET, "arch bitnet");
    check(tpl_family_from_arch("mamba") == TPL_UNKNOWN && tpl_family_from_arch(nullptr) == TPL_UNKNOWN, "arch unknown");
    check(tpl_family_detect("<|im_start|>", "llama") == TPL_CHATML, "markers win over arch (SmolLM2)");
    check(tpl_family_detect(nullptr, "llama") == TPL_LLAMA3, "arch as fallback");
    check(!strcmp(tpl_family_name(TPL_CHATML), "chatml") && !strcmp(tpl_family_name(TPL_UNKNOWN), "unknown"), "names");
    for (enum tpl_family f = TPL_GEMMA3; f <= TPL_BITNET; f++)
        check(tpl_family_from_name(tpl_family_name(f)) == f, "override name round trip");
    check(tpl_family_from_name("unknown") == TPL_UNKNOWN && tpl_family_from_name("ChatML") == TPL_UNKNOWN &&
              tpl_family_from_name(nullptr) == TPL_UNKNOWN,
          "override names are exact");
}

static int32_t vocab(void *, const char *text) {
    if (!strcmp(text, "<|im_end|>"))
        return 7;
    if (!strcmp(text, "<|end_of_text|>"))
        return 2; /* the same id as EOS: listed once */
    return -1;
}

static void stops(void) {
    int32_t ids[8];
    size_t  n = tpl_stop_ids(vocab, nullptr, 2, 8, ids);
    check(n == 2 && ids[0] == 2 && ids[1] == 7, "EOS plus known markers, no duplicates");
    n = tpl_stop_ids(vocab, nullptr, -1, 1, ids);
    check(n == 1 && ids[0] == 7, "no EOS; the cap is respected");
}

int main(void) {
    goldens();
    incremental_equals_whole();
    generation_prompts();
    close_texts();
    detection();
    stops();
    if (failures) {
        fprintf(stderr, "%d check(s) failed\n", failures);
        return 1;
    }
    puts("templates: geist-serve goldens, incremental = whole for 5 families, generation prompts, closes, detection, stops passed");
    return 0;
}
