/*
 * stream.h — generated bytes → answer and thinking text (#3). Internal.
 *
 * Three stages, each fed what the previous one emits:
 *
 *   token pieces → str_utf8 (complete, valid code points)
 *               → str_output (<think> … </think> split from the answer)
 *               → str_stops (the answer ends before a stop string)
 *
 * str_utf8 and str_output are moved unchanged in logic from geist-serve
 * (src/app/core.c app_utf8_feed, src/app/output.c); their tests are ported
 * with them (tests/test_stream.c). str_stops is new (D11).
 */
#pragma once
#include <stddef.h>
#include <stdint.h>

/* Token pieces may end inside a UTF-8 character. Emits only complete,
 * validated code points (no overlongs, surrogates or values above U+10FFFF).
 * After invalid input it stays failed. */
struct str_utf8 {
    unsigned char bytes[4];
    unsigned      used, need;
    bool          failed;
};
/* Decode the NUL-terminated piece into out[0..cap), NUL-terminated.
 * false on invalid UTF-8 or when out is too small. */
bool str_utf8_feed(struct str_utf8 *s, const char *piece, char *out, size_t cap);

/* Protocol separation after UTF-8 decoding. With think_tags, leading
 * whitespace (up to 32 bytes) and <think> … </think> blocks (nested up to
 * 16 deep, then the rest is discarded) before the answer are reasoning:
 * discarded, or passed to the thinking callback without markers, in chunks
 * of at most 512 bytes on character boundaries. Everything from the first
 * other character on is answer; a later <think> is literal text. Incomplete
 * prefixes and reasoning are discarded at the end, never shown. */
typedef bool (*str_emit_fn)(void *context, const char *text);
struct str_output {
    enum { STR_PREFIX, STR_REASONING, STR_ANSWER, STR_DISCARD, STR_FINISHED } state;
    char        prefix[40];
    char        held[8]; /* a possible partial closing marker, until it resolves */
    size_t      used, closing, opening, held_len;
    unsigned    depth;
    bool        enabled, reasoning;
    str_emit_fn think;
};
void str_output_init(struct str_output *out, bool think_tags);
/* Receive reasoning text (without markers) through think, with feed's context. */
void str_output_thinking(struct str_output *out, str_emit_fn think);
/* false if an emit callback returned false, or after finish. */
bool str_output_feed(struct str_output *out, const char *text, str_emit_fn emit, void *context);
void str_output_finish(struct str_output *out);

/* The answer ends before the first match of any stop string. A possible
 * start of one is held back until it resolves; the match and everything
 * after it are dropped. */
struct str_stops {
    const char *const *stops; /* borrowed, non-empty strings */
    size_t             n_stops;
    char              *held; /* answer text not yet emitted (owned) */
    size_t             held_len, held_cap;
    bool               stopped;
};
void str_stops_init(struct str_stops *s, size_t n, const char *const stops[]);
void str_stops_free(struct str_stops *s);
/* Pass answer text on through emit, minus what a stop string ends.
 * false if emit returned false or memory ran out. */
bool str_stops_feed(struct str_stops *s, const char *text, str_emit_fn emit, void *context);
/* The answer is over: emit what was held back (it matched no stop string). */
bool str_stops_finish(struct str_stops *s, str_emit_fn emit, void *context);

/* ---- pieces: what the stages emit, in order, until the caller takes it ---- */
struct str_piece {
    int    part; /* the caller's kind of text */
    char  *text; /* owned */
    size_t len;
};
struct str_pieces {
    struct str_piece *items;
    size_t            n, head, cap;
    char             *taken; /* the text of the last piece taken */
};
/* A copy of text ("" is skipped); false when out of memory. */
bool str_pieces_push(struct str_pieces *q, int part, const char *text);
/* The next piece into out, or false if none; its text stays valid until the
 * next take or free. */
bool str_pieces_take(struct str_pieces *q, struct str_piece *out);
void str_pieces_clear(struct str_pieces *q); /* drops what was not taken */
void str_pieces_free(struct str_pieces *q);

/* ---- repetition: an answer that loops ---------------------------------------
 * True when the tokens end in one cycle repeated back to back: a period of 4
 * to 256 tokens, at least 3 times and at least 48 tokens in all. A small model
 * can repeat itself without end (the more so when its earlier repetitions are
 * in the conversation); this ends such an answer. Prose, lists and tables do
 * not repeat a whole token sequence that often. */
bool str_repeats(const int32_t *tokens, size_t n);
